### ISSUE TITLE
can you share the captions part for the training data ?  

### ISSUE THREAD

**Issue by eriche2016** [rlebret/phrase-based_image_captioning#1]
because the file i downloaded from COCO website is a json file, not with the format you can process with the script you provided(ie, parse.lua). much obliged if you do

**Comment by rlebret** [comment]
As mentioned in doc, parse.lua excepts an input file with tab-separated values. 
If you want to parse your json in lua, there are many available packages for that: http://lua-users.org/wiki/JsonModules

**Comment by eriche2016** [comment]
thanks, i know. and i did it already. I original thought that if you provide the script for parse the json file, it will save some efforts, ...ur i have done it already. by the way, how do you training your word embeddings? can you give more details, much obliged if you do.

**Comment by gujiuxiang** [comment]
@eriche2016 , did you know how to get the input file? 
"th chunking/parse.lua "$input_file" "$output_dir""
